addons:
  postgresql: 9.6
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
language: ruby
rvm:
- 2.5.1
cache:
  directories:
  - vendor/bundle
  - node_modules
script:
- yarn install
- bundle exec rails webpacker:compile
- bundle exec rake db:schema:load
- bundle exec rspec
services:
- redis-server
deploy:
  provider: heroku
  api_key: "$HEROKU_AUTH_TOKEN"
  app: kitboxer
  run:
  - rake db:migrate